name: Coverage Reporting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage report
        run: npm run test:coverage

      - name: Coverage thresholds check
        run: |
          # Check if coverage meets minimum thresholds
          COVERAGE_FILE="coverage/coverage-summary.json"
          if [ -f "$COVERAGE_FILE" ]; then
            LINES=$(node -p "JSON.parse(require('fs').readFileSync('$COVERAGE_FILE', 'utf8')).total.lines.pct")
            FUNCTIONS=$(node -p "JSON.parse(require('fs').readFileSync('$COVERAGE_FILE', 'utf8')).total.functions.pct")
            BRANCHES=$(node -p "JSON.parse(require('fs').readFileSync('$COVERAGE_FILE', 'utf8')).total.branches.pct")
            STATEMENTS=$(node -p "JSON.parse(require('fs').readFileSync('$COVERAGE_FILE', 'utf8')).total.statements.pct")

            echo "Lines coverage: ${LINES}%"
            echo "Functions coverage: ${FUNCTIONS}%"
            echo "Branches coverage: ${BRANCHES}%"
            echo "Statements coverage: ${STATEMENTS}%"

            # Check if coverage is at least 80%
            if (( $(echo "$LINES < 80" | bc -l) )); then
              echo "❌ Lines coverage ${LINES}% is below 80% threshold"
              exit 1
            fi

            if (( $(echo "$FUNCTIONS < 80" | bc -l) )); then
              echo "❌ Functions coverage ${FUNCTIONS}% is below 80% threshold"
              exit 1
            fi

            if (( $(echo "$BRANCHES < 80" | bc -l) )); then
              echo "❌ Branches coverage ${BRANCHES}% is below 80% threshold"
              exit 1
            fi

            if (( $(echo "$STATEMENTS < 80" | bc -l) )); then
              echo "❌ Statements coverage ${STATEMENTS}% is below 80% threshold"
              exit 1
            fi

            echo "✅ All coverage thresholds passed!"
          else
            echo "❌ Coverage file not found"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30