name: Node.js Environment Setup

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18.x'

jobs:
  setup:
    name: Setup Node.js Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Get npm cache directory
        id: cache
        run: |
          echo "cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.cache.outputs.cache-dir }}
          key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ inputs.node-version }}-
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci